config/routes.rb
Rails.application.routes.draw do
  resources :users
  root 'users#index'
  get 'add_partial', to: 'users#add_partial'
  get 'get_user', to: 'users#show_user'
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show_user
    render partial: 'user', locals: { user: {first_name: params[:first_name], last_name: params[:last_name] }}
  end

  def add_partial
    render partial: 'my_partial'
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserProducts</title>
   <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container">

<%= yield %>

</body>
</html>

app/views/users/_contact_card.html.erb
<div class="row">
  <div class="col s12 m4">
    <div class="card blue-grey darken-1">
      <div id="user_details" class="card-content white-text">
        "<span class='card-title'>" + user.first_name + ' ' + user.last_name + "</span><p>" + user.phone_number + "</p>"
      </div>
      <div class="card-action">
        <a href="#">Delete</a>
        <a href="#">Show</a>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_my_partial.html.erb
<h2>This can be deleted.</h2>

app/views/users/_user.html.erb
<h2><%= user[:first_name] %></h2>
<h2><%= user[:last_name] %></h2>
<%= link_to 'Back', root_path %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<br>
<button id='get_users'>Get Users</button>
<button id='add_sort'>Sort Users</button>

<form id='edit_user' class='hide'>
  First Name: <input id='first_name'><br>
  Last Name: <input id='last_name'><br>
  Phone Number: <input id='phone_number'>
  <button class='edit' type='button'>Submit</button>
</form>

<form id='add_user'>
  First Name: <input id='new_first_name'><br>
  Last Name: <input id='new_last_name'><br>
  Phone Number: <input id='new_phone_number'><br>
  <button class='add' type='button'>Create User</button>
</form>

<ul id='users'>
</ul>
<div id='placeholder'>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>